SELECT 
    CAST(CONTRACT_ID AS STRING) AS CONTRACT_ID,
    CAST(ID_CLIENTE AS STRING) AS CUSTOMER_ID,
    SUM(VALOR_TOTAL) AS VALOR,
    'MAINFRAME' AS FONTE,
    PRODUTO AS TIPO_CONTRATO,
    DATE_FORMAT(CURRENT_DATE(), 'yyyyMM') AS ANO_MES
FROM TB_CONTRATOS_MAINFRAME
GROUP BY 
    CONTRACT_ID, ID_CLIENTE, PRODUTO