SELECT 
    tb001_sor.CUSTOMER_ID,
    tb001_sor.CONTRACT_ID,
    tb001_sor.VALOR_TOTAL AS VALOR_TOTAL_tb1,
    tb002_sor.VALOR_TOTAL AS VALOR_TOTAL_tb2,
    tb003_sor.VALOR_TOTAL AS VALOR_TOTAL_tb3,
    DATE_FORMAT(tb001_sor.LAST_UPDATE, 'yyyyMMdd') AS ANOMESDIA
FROM 
    tb001_sor
INNER JOIN 
    tb002_sor
    ON tb001_sor.CONTRACT_ID = tb002_sor.CONTRACT_ID
    AND tb001_sor.CUSTOMER_ID = tb002_sor.CUSTOMER_ID
INNER JOIN 
    tb003_sor
    ON tb001_sor.CONTRACT_ID = tb003_sor.CONTRACT_ID
    AND tb001_sor.CUSTOMER_ID = tb003_sor.CUSTOMER_ID
    