SELECT 
    CAST(CONTRACT_ID AS STRING) AS CONTRACT_ID,
    CAST(ID_CLIENTE AS STRING) AS CUSTOMER_ID,
    SUM(VALOR_TOTAL) AS VALOR,
    'MAINFRAME' AS FONTE,
    DATE_FORMAT(CURRENT_DATE(), 'yyyyMMdd') AS DATA_PROCESSAMENTO
FROM TB_CONTRATOS_MAINFRAME
GROUP BY 
    CONTRACT_ID, ID_CLIENTE

UNION

SELECT 
    CAST(CONTRACT_ID AS STRING) AS CONTRACT_ID,
    CAST(CUSTOMER_ID AS STRING) AS CUSTOMER_ID,
    SUM(CAST(VALOR_TOTAL AS DECIMAL(38,10))) AS VALOR,
    'MOBILE' AS FONTE,
    DATE_FORMAT(CURRENT_DATE(), 'yyyyMMdd') AS DATA_PROCESSAMENTO
FROM TB_CONTRATOS_MOBILE
GROUP BY 
    CONTRACT_ID, CUSTOMER_ID

UNION

SELECT 
    CAST(CONTRACT_ID AS STRING) AS CONTRACT_ID,
    CAST(CUSTOMER_ID AS STRING) AS CUSTOMER_ID,
    SUM(VALOR_TOTAL) AS VALOR,
    'EXTERNOS' AS FONTE,
    DATE_FORMAT(LAST_UPDATE, 'yyyyMMdd') AS DATA_PROCESSAMENTO
FROM TB_DADOS_EXTERNOS
GROUP BY 
    CONTRACT_ID, CUSTOMER_ID, DATE_FORMAT(LAST_UPDATE, 'yyyyMMdd')
